import { contextBridge, ipcRenderer } from 'electron'

// Channel names inlined here — preload runs in a sandboxed context (Electron v20+
// defaults sandbox:true) where require() can only resolve built-in Node modules,
// not relative paths. Keeping these in sync with ipc/types.ts is intentional.
const CH = {
  // Renderer → Main
  START_MANUAL:    'recording:startManual',
  STOP:            'recording:stop',
  DISCARD:         'recording:discard',
  UPDATE_TITLE:    'recording:updateTitle',
  TASKS_CONFIRM:   'tasks:confirm',
  COMMS_SEND:      'comms:send',
  RENDERER_READY:    'renderer:ready',
  PROCESSING_ACK:    'processing:ack',
  SPEAKERS_LABEL:    'speakers:label',
  SPEAKERS_CONFIRM:  'speakers:confirm',
  SPEAKERS_RESOLVE:  'speakers:resolve',
  PROFILES_UPDATE:   'profiles:update',
  AUTH_INITIATE_LOGIN:     'auth:initiateLogin',
  AUTH_GET_SESSION:        'auth:getSession',
  AUTH_LOGOUT_INVOKE:      'auth:logout',
  CALENDAR_CONNECT:        'calendar:connect',
  CALENDAR_STATUS:         'calendar:status',
  CALENDAR_GET_EVENTS:     'calendar:getEvents',
  CALENDAR_GET_PROFILE:    'calendar:getProfile',
  CALENDAR_DISCONNECT:     'calendar:disconnect',
  TASKS_CREATE_STANDALONE: 'tasks:createStandalone',
  TASKS_GET_BY_LIST:       'tasks:getByList',
  TASK_DISMISS:            'task:dismiss',
  LISTS_GET_ALL:           'lists:getAll',
  LISTS_CREATE:            'lists:create',
  LISTS_DELETE:            'lists:delete',
  TASKS_COMPLETE:          'tasks:complete',
  MEETINGS_GET_PAST:           'meetings:getPast',
  MEETINGS_GET_TRASHED:        'meetings:getTrashed',
  MEETINGS_GET_DETAIL:         'meetings:getDetail',
  MEETINGS_SOFT_DELETE:        'meetings:softDelete',
  MEETINGS_UNDELETE:           'meetings:undelete',
  MEETINGS_HARD_DELETE:        'meetings:hardDelete',
  MEETINGS_RESTORE_DISMISSED:  'meetings:restoreDismissed',
  TASKS_RESTORE:               'tasks:restore',
  TASKS_HARD_DELETE:           'tasks:hardDelete',
  TASKS_GET_BY_ID:             'tasks:getById',
  TASKS_UPDATE_TITLE:          'tasks:updateTitle',
  TASKS_REORDER:               'tasks:reorder',
  TASKS_UPDATE:                'tasks:update',
  TASKS_APPROVE_DISMISS:       'tasks:approveDismiss',
  TASKS_APPROVE_WITH_LISTS:    'tasks:approveWithLists',
  PERMISSIONS_OPEN_MIC:        'permissions:openMicSettings',
  PERMISSIONS_OPEN_SCREEN:     'permissions:openScreenSettings',
  APP_RELAUNCH:                'app:relaunch',
  UPDATE_CHECK:                'update:check',
  UPDATE_INSTALL:              'update:install',
  // Main → Renderer
  MEETING_UPCOMING:        'meeting:upcoming',
  CALENDAR_EVENTS_UPDATED: 'calendar:eventsUpdated',
  RECORDING_STARTED:       'recording:started',
  SPEAKER_ADDED:           'recording:speakerAdded',
  PROCESSING_COMPLETE:     'processing:complete',
  COMMS_SENT:              'comms:sent',
  SYNC_PULL_START:         'sync:pullStart',
  SYNC_PULL_COMPLETE:      'sync:pullComplete',
  SYNC_DATA_UPDATED:       'sync:dataUpdated',
  UPDATE_AVAILABLE:        'update:available',
  UPDATE_DOWNLOADED:       'update:downloaded',
  TRAY_REQUEST_START:      'tray:requestStart',
  TRAY_REQUEST_STOP:       'tray:requestStop',
  TRAY_REQUEST_DISCARD:    'tray:requestDiscard',
} as const

contextBridge.exposeInMainWorld('electronAPI', {
  // Renderer → Main
  rendererReady:      ()                                          => ipcRenderer.invoke(CH.RENDERER_READY),
  ackProcessingComplete: ()                                       => ipcRenderer.send(CH.PROCESSING_ACK),
  startManual:      (opts?: { calendarEventId?: string })       => ipcRenderer.invoke(CH.START_MANUAL, opts),
  stopRecording:    ()                                          => ipcRenderer.invoke(CH.STOP),
  discardRecording: ()                                          => ipcRenderer.invoke(CH.DISCARD),
  updateTitle:      (payload: { meetingId: string; title: string }) => ipcRenderer.invoke(CH.UPDATE_TITLE, payload),
  confirmTasks:     (payload: unknown)                          => ipcRenderer.invoke(CH.TASKS_CONFIRM, payload),
  sendComms:        (payload: unknown)                          => ipcRenderer.invoke(CH.COMMS_SEND, payload),
  labelSpeakers:    (payload: unknown)                          => ipcRenderer.invoke(CH.SPEAKERS_LABEL, payload),
  confirmSpeaker:   (payload: unknown)                          => ipcRenderer.invoke(CH.SPEAKERS_CONFIRM, payload),
  resolveSpeaker:   (payload: unknown)                          => ipcRenderer.invoke(CH.SPEAKERS_RESOLVE, payload),
  updateProfiles:   (payload: unknown)                          => ipcRenderer.invoke(CH.PROFILES_UPDATE, payload),
  initiateLogin:        ()                                          => ipcRenderer.invoke(CH.AUTH_INITIATE_LOGIN),
  getSession:           ()                                          => ipcRenderer.invoke(CH.AUTH_GET_SESSION),
  logoutAuth:           ()                                          => ipcRenderer.invoke(CH.AUTH_LOGOUT_INVOKE),
  connectCalendar:      ()                                          => ipcRenderer.invoke(CH.CALENDAR_CONNECT),
  getCalendarStatus:    ()                                          => ipcRenderer.invoke(CH.CALENDAR_STATUS),
  getCalendarEvents:    ()                                          => ipcRenderer.invoke(CH.CALENDAR_GET_EVENTS),
  getCalendarProfile:   ()                                          => ipcRenderer.invoke(CH.CALENDAR_GET_PROFILE),
  disconnectCalendar:   ()                                          => ipcRenderer.invoke(CH.CALENDAR_DISCONNECT),
  createStandaloneTask: (payload: { title: string; listName: string }) => ipcRenderer.invoke(CH.TASKS_CREATE_STANDALONE, payload),
  getTasksByList:       (listName: string)                          => ipcRenderer.invoke(CH.TASKS_GET_BY_LIST, listName),
  dismissTask:          (taskId: string)                            => ipcRenderer.invoke(CH.TASK_DISMISS, taskId),
  getAllLists:           ()                                          => ipcRenderer.invoke(CH.LISTS_GET_ALL),
  createList:           (name: string)                              => ipcRenderer.invoke(CH.LISTS_CREATE, name),
  deleteList:           (listId: string)                            => ipcRenderer.invoke(CH.LISTS_DELETE, listId),
  completeTask:         (payload: { taskId: string; originList: string }) => ipcRenderer.invoke(CH.TASKS_COMPLETE, payload),
  getPastMeetings:      ()                                          => ipcRenderer.invoke(CH.MEETINGS_GET_PAST),
  getTrashedMeetings:   ()                                          => ipcRenderer.invoke(CH.MEETINGS_GET_TRASHED),
  getMeetingDetail:     (meetingId: string)                         => ipcRenderer.invoke(CH.MEETINGS_GET_DETAIL, meetingId),
  softDeleteMeeting:    (meetingId: string)                         => ipcRenderer.invoke(CH.MEETINGS_SOFT_DELETE, meetingId),
  undeleteMeeting:      (meetingId: string)                         => ipcRenderer.invoke(CH.MEETINGS_UNDELETE, meetingId),
  hardDeleteMeeting:    (meetingId: string)                         => ipcRenderer.invoke(CH.MEETINGS_HARD_DELETE, meetingId),
  restoreDismissedTasks: (meetingId: string)                        => ipcRenderer.invoke(CH.MEETINGS_RESTORE_DISMISSED, meetingId),
  restoreTask:          (taskId: string)                            => ipcRenderer.invoke(CH.TASKS_RESTORE, taskId),
  hardDeleteTask:       (taskId: string)                            => ipcRenderer.invoke(CH.TASKS_HARD_DELETE, taskId),
  getTaskById:          (taskId: string)                            => ipcRenderer.invoke(CH.TASKS_GET_BY_ID, taskId),
  updateTaskTitle:      (payload: { taskId: string; title: string }) => ipcRenderer.invoke(CH.TASKS_UPDATE_TITLE, payload),
  reorderTasks:         (orderedIds: string[])                        => ipcRenderer.invoke(CH.TASKS_REORDER, orderedIds),
  updateTask:           (payload: unknown)                           => ipcRenderer.invoke(CH.TASKS_UPDATE, payload),
  approveDismissTasks:  (payload: unknown)                           => ipcRenderer.invoke(CH.TASKS_APPROVE_DISMISS, payload),
  approveWithLists:     (payload: unknown)                           => ipcRenderer.invoke(CH.TASKS_APPROVE_WITH_LISTS, payload),
  openMicSettings:         ()                                          => ipcRenderer.invoke(CH.PERMISSIONS_OPEN_MIC),
  openScreenSettings:      ()                                          => ipcRenderer.invoke(CH.PERMISSIONS_OPEN_SCREEN),
  relaunchApp:             ()                                          => ipcRenderer.invoke(CH.APP_RELAUNCH),
  checkForUpdates:         ()                                          => ipcRenderer.invoke(CH.UPDATE_CHECK),
  installUpdate:           ()                                          => ipcRenderer.invoke(CH.UPDATE_INSTALL),

  // Main → Renderer (event subscriptions)
  onMeetingUpcoming:        (cb: (payload: unknown) => void) => ipcRenderer.on(CH.MEETING_UPCOMING,        (_e, p) => cb(p)),
  onCalendarEventsUpdated:  (cb: (payload: unknown) => void) => ipcRenderer.on(CH.CALENDAR_EVENTS_UPDATED, (_e, p) => cb(p)),
  onRecordingStarted:   (cb: (payload: unknown) => void) => ipcRenderer.on(CH.RECORDING_STARTED,   (_e, p) => cb(p)),
  onSpeakerAdded:       (cb: (payload: unknown) => void) => ipcRenderer.on(CH.SPEAKER_ADDED,       (_e, p) => cb(p)),
  onProcessingComplete: (cb: (payload: unknown) => void) => ipcRenderer.on(CH.PROCESSING_COMPLETE, (_e, p) => cb(p)),
  onCommsSent:          (cb: (payload: unknown) => void) => ipcRenderer.on(CH.COMMS_SENT,          (_e, p) => cb(p)),
  onAuthStatus:         (cb: (payload: unknown) => void) => ipcRenderer.on('auth:status',  (_e, p) => cb(p)),
  onAuthLogin:          (cb: (payload: unknown) => void) => ipcRenderer.on('auth:login',   (_e, p) => cb(p)),
  onAuthLogout:         (cb: (payload: unknown) => void) => ipcRenderer.on('auth:logout',  (_e, p) => cb(p)),
  onSyncPullStart:      (cb: () => void)                   => ipcRenderer.on(CH.SYNC_PULL_START,    () => cb()),
  onSyncPullComplete:   (cb: (payload: unknown) => void)   => ipcRenderer.on(CH.SYNC_PULL_COMPLETE, (_e, p) => cb(p)),
  onSyncDataUpdated:    (cb: () => void)                   => ipcRenderer.on(CH.SYNC_DATA_UPDATED,  () => cb()),
  onUpdateAvailable:    (cb: (payload: unknown) => void)   => ipcRenderer.on(CH.UPDATE_AVAILABLE,   (_e, p) => cb(p)),
  onUpdateDownloaded:   (cb: (payload: unknown) => void)   => ipcRenderer.on(CH.UPDATE_DOWNLOADED,  (_e, p) => cb(p)),
  onTrayRequestStart:   (cb: () => void)                   => ipcRenderer.on(CH.TRAY_REQUEST_START,   () => cb()),
  onTrayRequestStop:    (cb: () => void)                   => ipcRenderer.on(CH.TRAY_REQUEST_STOP,    () => cb()),
  onTrayRequestDiscard: (cb: () => void)                   => ipcRenderer.on(CH.TRAY_REQUEST_DISCARD, () => cb()),

  removeAllListeners: (channel: string) => ipcRenderer.removeAllListeners(channel),
})
